### ISSUE TITLE
where is branch length ? 

### ISSUE THREAD

**Issue by lalalagartija** [ChrisCreevey/clann#5]
Hi ! Thank you for this great tool.
I used this command : 
"~/Software/clann/clann -ln -c clann_commands ../all_subset_trees.nwk"
And this options "hs ; bootstrap ; nj"
but I don't get branch length on my final tree. Is that normal ?

**Comment by ChrisCreevey** [comment]
Thanks for your message, 
From the commands above, you have done three different analyses with three different output trees. 

The 'hs' command will by default output a tree from the MSS method which only deals with topologies and so there are no branch lengths, with the file name "Heuristic_result.txt".

The 'bootstrap' command will output two files, "bootstrap.txt" containing the results from all 100 (by default) replicates and "consensus.ph" which has the majority-rule consensus tree of the 100 replicates. This will have no branch lengths either.

The 'nj' command will create a neighbour-joining tree (with branch lengths) and write it to the file 'NJ-tree.ph'. This is the only file where you will find branch lengths.

One other way to get branch length is to use the Avcon criteria, which requires the use of PAUP*, please see the manual for more information on that.
