### ISSUE TITLE
Problem with make 

### ISSUE THREAD

**Issue by michaelbroe** [ChrisCreevey/clann#7]
`./configure` works fine, but I get the following error when running make:

```bash
make
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.16
/bin/sh: aclocal-1.16: command not found
make: *** [aclocal.m4] Error 127
```

The only `aclocal` in the cloned directory is `aclocal.m4`.

Using RHEL 7.7

I get the following error under Ubuntu:

```bash
make
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.16
/bin/bash: aclocal-1.16: command not found
Makefile:312: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127
```

Cheers,
Michael

**Comment by ChrisCreevey** [comment]
I think this is fixed now. Can you pull the latest commit and  try ./configure; make; to see?
Chris.

**Comment by michaelbroe** [comment]
```bash
cd clann
./configure
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."```
```
In addition, `install-sh` is a symbolic link to:
```bash
 lrwxrwxrwx ... install-sh -> /usr/local/Cellar/automake/1.16.1_1/share/automake-1.16/install-sh
```

Cheers,
Michael

**Comment by ChrisCreevey** [comment]
OK, I've replaced that file with the original, and pushed the change. Can you see if this works for you now?

Chris.

**Comment by michaelbroe** [comment]
`./configure` now works, but make was still broken:

```bash
make
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.16
/bin/sh: aclocal-1.16: command not found
make: *** [aclocal.m4] Error 127
```
However I fixed it by running:
```bash
autoreconf -f -i
./configure
make
```
as per this thread:

https://stackoverflow.com/questions/33278928/how-to-overcome-aclocal-1-15-is-missing-on-your-system-warning

Cheers,
Michael

**Comment by ChrisCreevey** [comment]
Thanks for the suggestion, I've added the information to the INSTALL file in case others have the same problem.
